name: Covid in Alberta

# Short bio or description (displayed in the header)
description: Alberta's Response to COVID-19 

url:

baseurl: ""

permalink: /:categories/:title/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


theme: jekyll-theme-slate